---
:machine:
  :q0:
    '1':
      - :q0
      - '1'
      - :right
    '0':
      - :q1
      - '0'
      - :right
  :q1:
    '1':
      - :q0
      - '1'
      - :right
    '0':
      - :q2
      - '0'
      - :right
  :q2:
    '0':
      - :q2
      - '0'
      - :right
    '1':
      - :q2
      - '1'
      - :right
    ! '':
      - :q3
      -
      - :right
  :q3: {}
