---
:machine:
  :q1:
    '0':
      - :q3
      -
      - :right
    '1':
      - :q12
      -
      - :right
  :q2: {}
  :q3:
    '0':
      - :q3
      - '0'
      - :right
    '1':
      - :q4
      - '1'
      - :right
  :q4:
    '0':
      - :q4
      - '0'
      - :right
    ! '':
      - :q5
      - '2'
      - :left
    '2':
      - :q5
      - '2'
      - :left
  :q5:
    '0':
      - :q5
      - '0'
      - :left
    '1':
      - :q6
      - '1'
      - :right
  :q6:
    '0':
      - :q7
      - '3'
      - :right
    ! '':
      - :q12
      -
      - :right
    '3':
      - :q6
      - '3'
      - :right
    '2':
      - :q10
      - '2'
      - :left
  :q7:
    '0':
      - :q7
      - '0'
      - :right
    '2':
      - :q8
      - '2'
      - :right
  :q8:
    '0':
      - :q8
      - '0'
      - :right
    ! '':
      - :q9
      - '0'
      - :left
  :q9:
    '3':
      - :q9
      - '3'
      - :left
    '0':
      - :q9
      - '0'
      - :left
    '2':
      - :q9
      - '2'
      - :left
    '1':
      - :q6
      - '1'
      - :right
  :q10:
    '3':
      - :q10
      - '0'
      - :left
    '1':
      - :q11
      - '1'
      - :left
  :q11:
    '0':
      - :q11
      - '0'
      - :left
    ! '':
      - :q1
      -
      - :right
  :q12:
    '0':
      - :q12
      -
      - :right
    '2':
      - :q2
      -
      - :right
    ! '':
      - :q2
      -
      - :right
